"""Add ref_dropped

Revision ID: 4b5a0c9185e5
Revises: 
Create Date: 2026-02-04 20:12:38.170615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5a0c9185e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('referee_interest')
    # with op.batch_alter_table('chat_message', schema=None) as batch_op:
    #     batch_op.alter_column('sender_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='SET NULL')
    #     batch_op.create_foreign_key(None, 'chat_channel', ['channel_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('chat_participant', schema=None) as batch_op:
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'chat_channel', ['channel_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_dropped', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_column('ref_dropped')

    # with op.batch_alter_table('chat_participant', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'chat_channel', ['channel_id'], ['id'])
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # with op.batch_alter_table('chat_message', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'chat_channel', ['channel_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
    #     batch_op.alter_column('sender_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # op.create_table('referee_interest',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('fixture_id', sa.INTEGER(), nullable=False),
    # sa.Column('timestamp', sa.DATETIME(), nullable=True),
    # sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
