"""add penalty columns

Revision ID: 945866fe1dba
Revises: b174c7cfa299
Create Date: 2026-04-04 11:50:57.861606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945866fe1dba'
down_revision = 'b174c7cfa299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_pens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_pens', sa.Integer(), nullable=True))

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('fixture', schema=None) as batch_op:
        batch_op.drop_column('away_pens')
        batch_op.drop_column('home_pens')

    # ### end Alembic commands ###
